kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stg
  namespace: stg
subjects:
- kind: ServiceAccount
  name: stg
  namespace: stg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stg
