kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stg
  namespace: stg
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  - deployment
  - pods
  verbs: ["*"]
